In [15]:
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.cluster import KMeans
import numpy as np
import seaborn as sb

In [16]:
# df = pd.read_csv("ObesityDataSet.csv", sep=',')
df = pd.read_csv("ObesityDataSet.csv")

df.Age = df.Age.astype('int64')
df.Height = df.Height.astype('int64')
df.Weight = df.Weight.astype('int64')
df.FCVC = df.FCVC.astype('int64')
df.NCP = df.NCP.astype('int64')
df.CH2O = df.CH2O.astype('int64')
df.FAF = df.FAF.astype('int64')
df.TUE = df.TUE.astype('int64')

df.Gender = df.Gender.replace({'Male': 0, 'Female': 1})
df.family_history_with_overweight = df.family_history_with_overweight.replace({'yes': 0, 'no': 1})
df.FAVC = df.FAVC.replace ({'yes': 0, 'no': 1})
df.CAEC = df.CAEC.replace ({'Sometimes': 0, 'Frequently': 1, 'Always': 2, 'no': 3})
df.SMOKE = df.SMOKE.replace({'yes': 0, 'no': 1})
df.SCC = df.SCC.replace({'yes': 0, 'no': 1})
df.CALC = df.CALC.replace({'Sometimes': 0, 'Frequently': 1, 'Always': 2, 'no': 3})
df.MTRANS = df.MTRANS.replace({'Public_Transportation': 0, 'Walking': 1, 'Automobile': 2, 'Motorbike': 3, 'Bike': 4})
# df.NObeyesdad = df.NObeyesdad.replace({'Normal_Weight': 0, 'Overweight_Level_I': 1, 'Overweight_Level_II': 2, 'Insufficient_Weight': 3, 
#                                        'Obesity_Type_I': 4, 'Obesity_Type_II': 4, 'Obesity_Type_III': 5})

In [ ]:
sb.pairplot(df)

In [17]:
df

Gender  Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0          1   21       1      64                               0     1     2   
1          1   21       1      56                               0     1     3   
2          0   23       1      77                               0     1     2   
3          0   27       1      87                               1     1     3   
4          0   22       1      89                               1     1     2   
...      ...  ...     ...     ...                             ...   ...   ...   
2106       1   20       1     131                               0     0     3   
2107       1   21       1     133                               0     0     3   
2108       1   22       1     133                               0     0     3   
2109       1   24       1     133                               0     0     3   
2110       1   23       1     133                               0     0     3   

      NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS           NObeyesdad  
0       3     0      1     2    1    0    1     3       0        Normal_Weight  
1       3     0      0     3    0    3    0     0       0        Normal_Weight  
2       3     0      1     2    1    2    1     1       0        Normal_Weight  
3       3     0      1     2    1    2    0     1       1   Overweight_Level_I  
4       1     0      1     2    1    0    0     0       0  Overweight_Level_II  
...   ...   ...    ...   ...  ...  ...  ...   ...     ...                  ...  
2106    3     0      1     1    1    1    0     0       0     Obesity_Type_III  
2107    3     0      1     2    1    1    0     0       0     Obesity_Type_III  
2108    3     0      1     2    1    1    0     0       0     Obesity_Type_III  
2109    3     0      1     2    1    1    0     0       0     Obesity_Type_III  
2110    3     0      1     2    1    1    0     0       0     Obesity_Type_III  

[2111 rows x 17 columns]

In [18]:
X = np.array(df.drop('NObeyesdad', axis=1))
X

array([[ 1, 21,  1, ...,  1,  3,  0],
       [ 1, 21,  1, ...,  0,  0,  0],
       [ 0, 23,  1, ...,  1,  1,  0],
       ...,
       [ 1, 22,  1, ...,  0,  0,  0],
       [ 1, 24,  1, ...,  0,  0,  0],
       [ 1, 23,  1, ...,  0,  0,  0]], dtype=int64)

# KMEANS

In [19]:
kmeans = KMeans(n_clusters = 3, random_state=0)

In [20]:
kmeans.fit(X)

c:\Users\Cliente\Desktop\MachineLearning\venvml\lib\site-packages\sklearn\cluster\_kmeans.py:1416: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  super()._check_params_vs_input(X, default_n_init=10)


KMeans(n_clusters=3, random_state=0)

In [21]:
kmeans.labels_

array([2, 2, 1, ..., 0, 0, 0])

In [22]:
df['K-classes'] = kmeans.labels_
df

Gender  Age  Height  Weight  family_history_with_overweight  FAVC  FCVC  \
0          1   21       1      64                               0     1     2   
1          1   21       1      56                               0     1     3   
2          0   23       1      77                               0     1     2   
3          0   27       1      87                               1     1     3   
4          0   22       1      89                               1     1     2   
...      ...  ...     ...     ...                             ...   ...   ...   
2106       1   20       1     131                               0     0     3   
2107       1   21       1     133                               0     0     3   
2108       1   22       1     133                               0     0     3   
2109       1   24       1     133                               0     0     3   
2110       1   23       1     133                               0     0     3   

      NCP  CAEC  SMOKE  CH2O  SCC  FAF  TUE  CALC  MTRANS  \
0       3     0      1     2    1    0    1     3       0   
1       3     0      0     3    0    3    0     0       0   
2       3     0      1     2    1    2    1     1       0   
3       3     0      1     2    1    2    0     1       1   
4       1     0      1     2    1    0    0     0       0   
...   ...   ...    ...   ...  ...  ...  ...   ...     ...   
2106    3     0      1     1    1    1    0     0       0   
2107    3     0      1     2    1    1    0     0       0   
2108    3     0      1     2    1    1    0     0       0   
2109    3     0      1     2    1    1    0     0       0   
2110    3     0      1     2    1    1    0     0       0   

               NObeyesdad  K-classes  
0           Normal_Weight          2  
1           Normal_Weight          2  
2           Normal_Weight          1  
3      Overweight_Level_I          1  
4     Overweight_Level_II          1  
...                   ...        ...  
2106     Obesity_Type_III          0  
2107     Obesity_Type_III          0  
2108     Obesity_Type_III          0  
2109     Obesity_Type_III          0  
2110     Obesity_Type_III          0  

[2111 rows x 18 columns]

In [ ]:
sb.pairplot(df,hue='NObeyesdad')

In [ ]:
sb.pairplot(df, hue='K-classes')

In [29]:
# usuario= [[1, 21, 1, 64, 0, 1, 2, 3, 0, 1, 2, 1, 0, 1, 3, 0] ] #classe 2
# kmeans.predict(usuario)

# usuario2 = [[0,	23,	1,	77,	0,	1,	2,	3,	0,	1,	2,	1,	2,	1,	1,	0	] ] #classe 1
# kmeans.predict(usuario2)

usuario3 =  [[1, 20, 1,	131,	0,	0,	3,	3,	0,	1,	1,	1,	1,	0,	0,	0] ] #  classe 0
kmeans.predict(usuario3)


array([0])